version: '2'
services:
 mymongo:  
  image: mongo
  container_name: spring-demo-mongo
  ports:
   - "27017"
  volumes:
   - data:/data/db 
  networks:
   - net1
 service:  
  image: myfirstms:0.0.1-SNAPSHOT
  container_name: spring-demo-service
  depends_on:
    - mymongo
  ports:
    - "8090:8080"   
  networks:
   - net1
volumes:
 data:
  driver: local
networks:
 net1:
  external:
      name: spring_demo_net 
  # Use a custom driver
  #driver: pring_demo_net
   
